### ISSUE TITLE
Endianness of MVF Length in CM_SLAC_MATCH.CNF

### ISSUE THREAD

**Issue by shayan-tabatabaei-nikkhah** [SwitchEV/pyslac#52]
Hi everyone,

In the `MatchCnf` class, it is stated that:

>  MVF is sent in little endian

I checked the Din SPEC 70121 and ISO 15118-3 documents, and I could not find such a thing. Have I missed something? Is there any 
 other document you can refer me to for that?

**Comment by RoastVeg** [comment]
Bit representation for individual messages is part of the HomePlug Green PHY specification.
